/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.reg_ajustes;
import Controlador.reg_permisos;
import Controlador.reg_personal;
import Modelo.Permisos;
import Modelo.Validaciones;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edgar
 */
public class vntana_motiv_ajuste extends javax.swing.JDialog {

    reg_ajustes rajus = new reg_ajustes();
    boolean delet = false;
    boolean update = false;
    reg_permisos rperm = new reg_permisos();
    reg_personal rpersonal = new reg_personal();
    ArrayList<Permisos> listPerm;
    String ced;
    String id_motivo;

    /**
     * Creates new form vntana_motiv_ajuste
     */
    public vntana_motiv_ajuste(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/iconos/tools.png")).getImage());      
        blockBotones(false);//desactivado todos los botones
        ced = menu_principal.ced_usu;
        loadPermisos(ced);
        fill_table();
        lblCont.setText(rajus.count_motivos_ajuste() + "");
        cargarCombTipo();
    }

    public void loadPermisos(String ced) {//Busca por cedula
        listPerm = rperm.cargar_permisos(ced);
        for (Permisos per : listPerm) {
            if (per.isPer_regist()) {
                btn_new.setEnabled(true);
            }
            if (per.isPer_udate()) {
                btn_actualizar.setEnabled(true);
                update = true;
            }
            if (per.isPer_delete()) {
                System.out.println("Ingresa al eliminar");
                btn_delete.setEnabled(true);
                delet = true;
            }
        }
    }

    //CARGAR COMBO
    //comboMotivo
    public void cargarCombTipo() {
        comboMotivo.removeAllItems();
        comboMotivo.addItem("");
        comboMotivo.addItem("Entrada");
        comboMotivo.addItem("Salida");

    }

    public void blockBotones(boolean ok) {
        btn_new.setEnabled(ok);
        btn_guardar.setEnabled(ok);
        btn_actualizar.setEnabled(ok);
        btn_delete.setEnabled(ok);

    }

    public void botones(boolean ok, boolean ok1) {
        btn_guardar.setEnabled(ok);
        btn_actualizar.setEnabled(ok1);//true
        btn_delete.setEnabled(ok1);//true
    }
    DefaultTableModel etiqueta;

    public void fill_table() {
        try {
            tbl_marca.setModel(rajus.setFilas_motivo(""));
            modelo_tabla();
        } catch (Exception err) {
            System.out.println(err);
        }
    }

    public void modelo_tabla() {
        tbl_marca.getColumnModel().getColumn(0).setPreferredWidth(3);
        tbl_marca.getColumnModel().getColumn(1).setPreferredWidth(200);
        tbl_marca.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbl_marca.getTableHeader().setBackground(Color.decode("#666666"));
        tbl_marca.getTableHeader().setForeground(Color.WHITE);
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        tbl_marca.getColumnModel().getColumn(0).setCellRenderer(tcr);
    }

    public boolean actBotones(boolean upda, boolean delet) {

        btn_actualizar.setEnabled(upda);//true
        btn_delete.setEnabled(delet);//true

        return true;
    }

    public boolean validar() {
        boolean ok = true;
        //  String mens = "Campo Requerido:";
        if (!Validaciones.esRequerido(text_motivo)) {
            ok = false;
            //mens += "Nombre de la marca ";
        };
        if (!Validaciones.es_Combo(comboMotivo)) {
            ok = false;
        }
        /* label_men.setForeground(Color.RED);
         label_men.setText(mens);*/
        return ok;
    }

    public void limpiar_campos() {

        text_motivo.setText("");

        comboMotivo.setSelectedItem("");

        pinta_text();
    }

    public void pinta_text() {

        Validaciones.pinta_Combo(comboMotivo);
        Validaciones.pinta_text(text_motivo);
    }

    public void campos(boolean ok) {
        text_motivo.setEnabled(ok);
        comboMotivo.setEnabled(ok);
        pinta_text();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_marca = new javax.swing.JTable();
        pnel_inf1 = new javax.swing.JPanel();
        lbel_bus = new javax.swing.JLabel();
        text_busc = new javax.swing.JTextField();
        btnbusTodo = new javax.swing.JButton();
        pnel_inf = new javax.swing.JPanel();
        lblmarc = new javax.swing.JLabel();
        text_motivo = new javax.swing.JTextField();
        lblmarc1 = new javax.swing.JLabel();
        comboMotivo = new javax.swing.JComboBox();
        tbar = new javax.swing.JToolBar();
        btn_new = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        lblCont = new javax.swing.JLabel();
        pnl_cab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Motivo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Doble clic para seleccionar Motivo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 390, -1));

        tbl_marca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_marcaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_marca);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 370, 140));

        pnel_inf1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnel_inf1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbel_bus.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lbel_bus.setText("Buscar:");
        pnel_inf1.add(lbel_bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        text_busc.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        text_busc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_buscKeyReleased(evt);
            }
        });
        pnel_inf1.add(text_busc, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 10, 210, -1));

        getContentPane().add(pnel_inf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 290, 40));

        btnbusTodo.setBackground(new java.awt.Color(0, 153, 102));
        btnbusTodo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnbusTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnbusTodo.setText("Todo");
        btnbusTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbusTodoActionPerformed(evt);
            }
        });
        getContentPane().add(btnbusTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 70, 40));

        pnel_inf.setBackground(new java.awt.Color(234, 234, 234));
        pnel_inf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnel_inf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblmarc.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblmarc.setText("Tipo:");
        pnel_inf.add(lblmarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        text_motivo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        pnel_inf.add(text_motivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 290, -1));

        lblmarc1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblmarc1.setText("Motivo:");
        pnel_inf.add(lblmarc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        comboMotivo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        comboMotivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnel_inf.add(comboMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 290, -1));

        getContentPane().add(pnel_inf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 370, 70));

        tbar.setBackground(new java.awt.Color(204, 204, 204));
        tbar.setRollover(true);

        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/new.png"))); // NOI18N
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });
        tbar.add(btn_new);

        btn_guardar.setBackground(new java.awt.Color(255, 255, 255));
        btn_guardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salvar.png"))); // NOI18N
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        tbar.add(btn_guardar);

        btn_actualizar.setBackground(new java.awt.Color(255, 255, 255));
        btn_actualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar-archivo.png"))); // NOI18N
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        tbar.add(btn_actualizar);

        btn_delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        tbar.add(btn_delete);
        tbar.add(jSeparator1);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Cantidad de Registros:");
        tbar.add(jLabel10);
        tbar.add(jSeparator2);

        lblCont.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCont.setText("0");
        tbar.add(lblCont);

        getContentPane().add(tbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 390, 40));

        pnl_cab.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Motivos de Ajustes");

        javax.swing.GroupLayout pnl_cabLayout = new javax.swing.GroupLayout(pnl_cab);
        pnl_cab.setLayout(pnl_cabLayout);
        pnl_cabLayout.setHorizontalGroup(
            pnl_cabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        pnl_cabLayout.setVerticalGroup(
            pnl_cabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_cab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_buscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_buscKeyReleased
        // TODO add your handling code here:
        tbl_marca.setModel(rajus.setFilas_motivo(text_busc.getText()));
        modelo_tabla();
    }//GEN-LAST:event_text_buscKeyReleased

    private void tbl_marcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_marcaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            id_motivo = tbl_marca.getValueAt(tbl_marca.getSelectedRow(), 0).toString();
            text_motivo.setText(tbl_marca.getValueAt(tbl_marca.getSelectedRow(), 1).toString());
            comboMotivo.setSelectedItem(tbl_marca.getValueAt(tbl_marca.getSelectedRow(), 2).toString());
            pinta_text();
            campos(true);
            if (delet == true && update == true) {
                botones(false, true);
            } else {
                actBotones(update, delet);
            }
        }
    }//GEN-LAST:event_tbl_marcaMouseClicked

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:

        limpiar_campos();
        campos(true);
        //  text_cod.setText(marc.cod_marca() + "");
        botones(true, false);

    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        //registrar marcas
        if (validar()) {
            rajus.agregar_motivo_Ajuste(text_motivo.getText(), comboMotivo.getSelectedItem().toString());

            JOptionPane.showMessageDialog(this, "Datos Registrados");
            fill_table();
            lblCont.setText(rajus.count_motivos_ajuste() + "");

        }

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            int seleccion = JOptionPane.showOptionDialog(null, "Desea Actualizar la Motivo",
                    "  ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    new Object[]{"Si    ", "   No",}, "Si");
            if (seleccion == JOptionPane.YES_OPTION) {
                rajus.editar_motivo_Ajuste(Integer.parseInt(id_motivo), text_motivo.getText(), comboMotivo.getSelectedItem().toString());
                JOptionPane.showMessageDialog(this, "Datos Actualizados");
                fill_table();
            }

        }
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            int seleccion = JOptionPane.showOptionDialog(null, "Desea Eliminar Motivo",
                    "  ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    new Object[]{"Si    ", "   No",}, "Si");
            if (seleccion == JOptionPane.YES_OPTION) {

                rajus.eliminar_motivo_Ajuste(Integer.parseInt(id_motivo));

                fill_table();
                lblCont.setText(rajus.count_motivos_ajuste() + "");
            }

            /* label_men.setForeground(Color.GREEN);
             label_men.setText("Datos Eliminados Correctamente");*/
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btnbusTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbusTodoActionPerformed

        fill_table();

    }//GEN-LAST:event_btnbusTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vntana_motiv_ajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vntana_motiv_ajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vntana_motiv_ajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vntana_motiv_ajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vntana_motiv_ajuste dialog = new vntana_motiv_ajuste(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btnbusTodo;
    private javax.swing.JComboBox comboMotivo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JLabel lbel_bus;
    private javax.swing.JLabel lblCont;
    private javax.swing.JLabel lblmarc;
    private javax.swing.JLabel lblmarc1;
    private javax.swing.JPanel pnel_inf;
    private javax.swing.JPanel pnel_inf1;
    private javax.swing.JPanel pnl_cab;
    private javax.swing.JToolBar tbar;
    private javax.swing.JTable tbl_marca;
    private javax.swing.JTextField text_busc;
    private javax.swing.JTextField text_motivo;
    // End of variables declaration//GEN-END:variables
}
