/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.reg_marca_tip;
import Controlador.reg_permisos;
import Controlador.reg_personal;
import Controlador.reg_productos;
import Modelo.Marca;
import Modelo.Permisos;
import Modelo.Producto;
import Modelo.tipo;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edgar
 */
public class vntana_inventario extends javax.swing.JDialog {

    /**
     * Creates new form vntana_inventario
     */
    ArrayList<Marca> listMarc;
    reg_marca_tip rmt = new reg_marca_tip();
    DefaultTableModel datos;
    ArrayList<Producto> listprod;
    reg_productos rp = new reg_productos();
    ArrayList<tipo> listTipPrend;
    reg_permisos rperm = new reg_permisos();
    reg_personal rpersonal = new reg_personal();
    ArrayList<Permisos> listPerm;
    String ced;

    public vntana_inventario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setIconImage(new ImageIcon(getClass().getResource("/iconos/tools.png")).getImage());      
        this.setLocationRelativeTo(null);
        ced = menu_principal.ced_usu;
        loadPermisos(ced);
        tabla_load(rp.busc_cod(""));
        cargarCombMarca();
        cargarCombPrendas();
        lbl_count.setText(rp.countProd() + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadPermisos(String ced) {//Busca por cedula
        listPerm = rperm.cargar_permisos(ced);
        for (Permisos per : listPerm) {

        }
    }

    public void tabla_load(String sql) {
        load_table(sql);
        modelo_tabla();
    }

    public void modelo_tabla() {
        try {
            tbl_inventario.getColumnModel().getColumn(0).setPreferredWidth(15);
            tbl_inventario.getColumnModel().getColumn(1).setPreferredWidth(35);
            tbl_inventario.getColumnModel().getColumn(2).setPreferredWidth(50);
            tbl_inventario.getColumnModel().getColumn(3).setPreferredWidth(35);
            tbl_inventario.getColumnModel().getColumn(4).setPreferredWidth(20);
            tbl_inventario.getColumnModel().getColumn(5).setPreferredWidth(20);
            tbl_inventario.getColumnModel().getColumn(6).setPreferredWidth(25);
            tbl_inventario.getColumnModel().getColumn(7).setPreferredWidth(25);
            tbl_inventario.getColumnModel().getColumn(8).setPreferredWidth(100);
            tbl_inventario.getColumnModel().getColumn(9).setPreferredWidth(40);
           // tbl_inventario.getColumnModel().getColumn(10).setPreferredWidth(40);
            tbl_inventario.getTableHeader().setBackground(Color.decode("#666666"));
            tbl_inventario.getTableHeader().setForeground(Color.WHITE);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            tbl_inventario.getColumnModel().getColumn(0).setCellRenderer(tcr);
            // tbl_inventario.getTableHeader().setBackground(Color.decode(colorHeadTable));
            DefaultTableCellRenderer tcr1 = new DefaultTableCellRenderer();
            tcr1.setHorizontalAlignment(SwingConstants.RIGHT);
            tbl_inventario.getColumnModel().getColumn(3).setCellRenderer(tcr1);
            tbl_inventario.getColumnModel().getColumn(4).setCellRenderer(tcr1);
        } catch (Exception err) {
            System.out.println(err);
        }
    }

    public void cargarCombMarca() {
        combo_marca.removeAllItems();
        combo_marca.addItem("");
        listMarc = rmt.CargarListMarca("");
        for (Marca m : listMarc) {
            combo_marca.addItem(m.getNom_marca());
        }
    }

    public void cargarCombPrendas() {
        combo_tip.removeAllItems();
        combo_tip.addItem("");
        listTipPrend = rmt.LoadListTip("");
        for (tipo tp : listTipPrend) {
            combo_tip.addItem(tp.getDescrip());
        }
    }

    //debe ser el sql
    public void load_table(String sql) {
        datos = rp.label_table();
        Object[] data = new Object[10];
        listprod = rp.llenar_prod_vnta(sql);
        for (Producto pr : listprod) {
            try {
                data[0] = pr.getNum_prod();
                data[1] = pr.getCod_prod();
                data[2] = rmt.ObtNomMarca(pr.getCod_marca() + "");
                data[3] = rmt.ObtNomTip(pr.getCod_tip_prend() + "");
                data[4] = pr.getPrec_cmpra();
                data[5] = pr.getPrec_vnta();
                data[6] = pr.getStok();
                data[7] = pr.isIva();
                data[8] = pr.getDescripcion();
                data[9] = pr.getObserv();
                datos.addRow(data);
                tbl_inventario.setModel(datos);
                // }
            } catch (Exception ex) {
                System.out.println("aqui:" + ex);
            }
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_cab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_inventario = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel4 = new javax.swing.JLabel();
        txt_busc = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        combo_marca = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        combo_tip = new javax.swing.JComboBox();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        lbl_count = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de Productos");

        pnl_cab.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inventario");

        javax.swing.GroupLayout pnl_cabLayout = new javax.swing.GroupLayout(pnl_cab);
        pnl_cab.setLayout(pnl_cabLayout);
        pnl_cabLayout.setHorizontalGroup(
            pnl_cabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(936, Short.MAX_VALUE))
        );
        pnl_cabLayout.setVerticalGroup(
            pnl_cabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        btn_imprimir.setBackground(new java.awt.Color(0, 153, 102));
        btn_imprimir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_imprimir.setForeground(new java.awt.Color(255, 255, 255));
        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir.png"))); // NOI18N
        btn_imprimir.setText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        tbl_inventario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_inventario);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);
        jToolBar1.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Buscar por Código:");
        jToolBar1.add(jLabel4);

        txt_busc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_busc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscKeyReleased(evt);
            }
        });
        jToolBar1.add(txt_busc);
        jToolBar1.add(jSeparator4);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Marca:");
        jToolBar1.add(jLabel1);

        combo_marca.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        combo_marca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_marcaActionPerformed(evt);
            }
        });
        combo_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                combo_marcaKeyReleased(evt);
            }
        });
        jToolBar1.add(combo_marca);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Tipo:");
        jToolBar1.add(jLabel2);
        jToolBar1.add(jSeparator2);

        combo_tip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        combo_tip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_tip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                combo_tipKeyReleased(evt);
            }
        });
        jToolBar1.add(combo_tip);
        jToolBar1.add(jSeparator5);

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator6);

        jButton4.setBackground(new java.awt.Color(0, 153, 102));
        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("Ver Todo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Ajustes");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator3);

        jLabel5.setText("Cantidad de Productos:");
        jToolBar1.add(jLabel5);
        jToolBar1.add(jSeparator7);

        lbl_count.setText("0");
        jToolBar1.add(lbl_count);
        jToolBar1.add(jSeparator1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_cab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_cab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tabla_load(rp.busc_cod(""));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_buscKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscKeyPressed

    }//GEN-LAST:event_txt_buscKeyPressed

    private void txt_buscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscKeyReleased
        // TODO add your handling code here:
        tabla_load(rp.busc_cod(txt_busc.getText()));
    }//GEN-LAST:event_txt_buscKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int dato = rmt.ObtCodMarca(combo_marca.getSelectedItem().toString());
        int dato1 = rmt.ObtCodTip(combo_tip.getSelectedItem().toString());
        tabla_load(rp.busc_marca_tipo(dato + "", dato1 + ""));

    }//GEN-LAST:event_jButton2ActionPerformed

    private void combo_marcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_marcaKeyReleased

        int dato = rmt.ObtCodMarca(combo_marca.getSelectedItem().toString());

        tabla_load(rp.busc_marca(dato));


    }//GEN-LAST:event_combo_marcaKeyReleased

    private void combo_tipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_tipKeyReleased
        // TODO add your handling code here:
        int dato = rmt.ObtCodTip(combo_tip.getSelectedItem().toString());
        tabla_load(rp.busc_tip(dato));
    }//GEN-LAST:event_combo_tipKeyReleased

    private void combo_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_marcaActionPerformed
        // TODO add your handling code here:
        /*int dato = rmt.ObtCodMarca(combo_marca.getSelectedItem().toString());
         
         tabla_load(rp.busc_marca(dato));*/
    }//GEN-LAST:event_combo_marcaActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:
        //  btn_imprimir
        if (!lbl_count.getText().equals("0")) {
            String mrca = combo_marca.getSelectedItem().toString();
            String tip = combo_tip.getSelectedItem().toString();
            JOptionPane.showMessageDialog(this, "Realizando operación.......Espere un momento");
            try {

                Map<String, Object> params = new HashMap<String, Object>();

                params.put("nom_marca", mrca);
                params.put("tip", tip);
                System.out.println(mrca);
                //  params.put("tipo", tip);
                Reportes_g.generarReporte("rep_inventario", params);
            } catch (Exception ex) {
                System.out.println(ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existen datos");
        }


    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        vntana_ajust_invent dlg = new vntana_ajust_invent(null, false);
        dlg.setModal(true); //no permite acceder a otros formularios hasta que se cierre
        dlg.setVisible(true);


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vntana_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vntana_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vntana_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vntana_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vntana_inventario dialog = new vntana_inventario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JComboBox combo_marca;
    private javax.swing.JComboBox combo_tip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_count;
    private javax.swing.JPanel pnl_cab;
    private javax.swing.JTable tbl_inventario;
    private javax.swing.JTextField txt_busc;
    // End of variables declaration//GEN-END:variables
}
