/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.reg_marca_tip;
import Controlador.reg_permisos;
import Controlador.reg_personal;
import Modelo.Permisos;
import Modelo.tipo;
import Modelo.Validaciones;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Edgar
 */
public class vntana_tipos extends javax.swing.JDialog {

    /**
     * Creates new form vntana_tip_prendas
     */
    reg_marca_tip rmt = new reg_marca_tip();
    tipo tp = new tipo();
    ArrayList<Permisos> listPerm;
    boolean delet = false;
    boolean update = false;
    reg_permisos rperm = new reg_permisos();
    reg_personal rpersonal = new reg_personal();
    String ced;

    public vntana_tipos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/iconos/tools.png")).getImage());      
        blockBotones(false);//desactivado todos los botones
        ced = menu_principal.ced_usu;
        loadPermisos(ced);
        fill_table();
        lblcountipRop.setText(rmt.count_tip_prend() + "");
    }

    public void fill_table() {
        try {
            table_tip_cloth.setModel(rmt.setFilas_tip_prend(""));
            modelo_tabla();
        } catch (Exception err) {
            System.out.println(err);
        }
    }

    public void loadPermisos(String ced) {//Busca por cedula
        listPerm = rperm.cargar_permisos(ced);
        for (Permisos per : listPerm) {

            if (per.isPer_regist()) {
                btn_new.setEnabled(true);
            }
            if (per.isPer_udate()) {
                btn_actualizar.setEnabled(true);
                update = true;
            }
            if (per.isPer_delete()) {
                System.out.println("Ingresa al eliminar");
                btn_delete.setEnabled(true);
                delet = true;
            }
        }
    }

    public void botones(boolean ok, boolean ok1) {
        btn_guardar.setEnabled(ok);
        btn_actualizar.setEnabled(ok1);//true
        btn_delete.setEnabled(ok1);//true
    }

    public boolean actBotones(boolean upda, boolean delet) {

        btn_actualizar.setEnabled(upda);//true
        btn_delete.setEnabled(delet);//true

        return true;
    }

    public void blockBotones(boolean ok) {
        btn_new.setEnabled(ok);
        btn_guardar.setEnabled(ok);
        btn_actualizar.setEnabled(ok);
        btn_delete.setEnabled(ok);

    }

    public void modelo_tabla() {
        table_tip_cloth.getColumnModel().getColumn(0).setPreferredWidth(1);
        table_tip_cloth.getColumnModel().getColumn(1).setPreferredWidth(100);
        table_tip_cloth.getTableHeader().setBackground(Color.decode("#666666"));
        table_tip_cloth.getTableHeader().setForeground(Color.WHITE);

        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        table_tip_cloth.getColumnModel().getColumn(0).setCellRenderer(tcr);

    }

    public boolean validar() {
        boolean ok = true;
        String mens = "Campo Requerido:";
        if (!Validaciones.esRequerido(text_tip_cloth)) {
            ok = false;
            mens += "Descripción ";
        };
        /* lbl_men.setForeground(Color.RED);
         lbl_men.setText(mens);*/
        return ok;
    }

    public void limpiar_campos() {
        text_cod.setText("");
        text_tip_cloth.setText("");
        pinta_text();
    }

    public void pinta_text() {
        Validaciones.pinta_text(text_cod);
        Validaciones.pinta_text(text_tip_cloth);
    }

    public void campos(boolean ok) {
        text_tip_cloth.setEnabled(ok);
        pinta_text();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_all = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnl_cab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tbar = new javax.swing.JToolBar();
        btn_new = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        lblcountipRop = new javax.swing.JLabel();
        pnel_inf = new javax.swing.JPanel();
        lbltipr = new javax.swing.JLabel();
        lblcod = new javax.swing.JLabel();
        text_cod = new javax.swing.JTextField();
        text_tip_cloth = new javax.swing.JTextField();
        pnel_inf1 = new javax.swing.JPanel();
        lbelbusc = new javax.swing.JLabel();
        txtbusc = new javax.swing.JTextField();
        btnBuscarTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_tip_cloth = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipo de Material");

        panel_all.setBackground(new java.awt.Color(204, 204, 204));
        panel_all.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Doble clic para seleccionar Marca");
        panel_all.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 40));

        pnl_cab.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de Material");

        javax.swing.GroupLayout pnl_cabLayout = new javax.swing.GroupLayout(pnl_cab);
        pnl_cab.setLayout(pnl_cabLayout);
        pnl_cabLayout.setHorizontalGroup(
            pnl_cabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        pnl_cabLayout.setVerticalGroup(
            pnl_cabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        tbar.setBackground(new java.awt.Color(204, 204, 204));
        tbar.setRollover(true);

        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo.png"))); // NOI18N
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });
        tbar.add(btn_new);

        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salvar.png"))); // NOI18N
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        tbar.add(btn_guardar);

        btn_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar-archivo.png"))); // NOI18N
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        tbar.add(btn_actualizar);

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        tbar.add(btn_delete);
        tbar.add(jSeparator2);

        jLabel10.setText("Cantidad de Registros:");
        tbar.add(jLabel10);
        tbar.add(jSeparator1);

        lblcountipRop.setText("0");
        tbar.add(lblcountipRop);

        pnel_inf.setBackground(new java.awt.Color(234, 234, 234));
        pnel_inf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnel_inf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltipr.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbltipr.setText("Tipo:");
        pnel_inf.add(lbltipr, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 49, -1, 20));

        lblcod.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblcod.setText("Código:");
        pnel_inf.add(lblcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 19, -1, -1));

        text_cod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        text_cod.setEnabled(false);
        pnel_inf.add(text_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 17, 70, -1));
        pnel_inf.add(text_tip_cloth, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 50, 304, -1));

        pnel_inf1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnel_inf1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbelbusc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbelbusc.setText("Buscar:");
        pnel_inf1.add(lbelbusc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        txtbusc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscKeyReleased(evt);
            }
        });
        pnel_inf1.add(txtbusc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 210, -1));

        btnBuscarTodo.setBackground(new java.awt.Color(0, 153, 102));
        btnBuscarTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarTodo.setText("Todo");
        btnBuscarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTodoActionPerformed(evt);
            }
        });

        table_tip_cloth.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_tip_cloth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_tip_clothMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_tip_cloth);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_cab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tbar, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_all, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnel_inf, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnel_inf1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnBuscarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_cab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tbar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnel_inf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnel_inf1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_all, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTodoActionPerformed
        // TODO add your handling code here:
        table_tip_cloth.setModel(rmt.setFilas_tip_prend(""));
        modelo_tabla();
    }//GEN-LAST:event_btnBuscarTodoActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (validar()) {

            int seleccion = JOptionPane.showOptionDialog(null, "Desea Eliminar tipo",
                    "  ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    new Object[]{"Si    ", "   No",}, "Si");
            if (seleccion == JOptionPane.YES_OPTION) {
                tp.setCod_tip(Integer.parseInt(text_cod.getText()));
                rmt.Delete(tp);
                fill_table();
                lblcountipRop.setText(rmt.count_tip_prend() + "");
            }

        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed

        limpiar_campos();

        campos(true);

        text_cod.setText(rmt.cod_tip_prend() + "");
        botones(true, false);
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            int seleccion = JOptionPane.showOptionDialog(null, "Desea Actualizar tipo",
                    "  ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    new Object[]{"Si    ", "   No",}, "Si");
            if (seleccion == JOptionPane.YES_OPTION) {
                tp.setCod_tip(Integer.parseInt(text_cod.getText()));
                tp.setDescrip(text_tip_cloth.getText());
                rmt.UpdateTip(tp);
                fill_table();
            }

        }
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            tp.setCod_tip(Integer.parseInt(text_cod.getText()));
            tp.setDescrip(text_tip_cloth.getText());
            rmt.insertTip(tp);
            JOptionPane.showMessageDialog(this, "Datos Registrados");
            fill_table();
            lblcountipRop.setText(rmt.count_tip_prend() + "");
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void table_tip_clothMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_tip_clothMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            text_cod.setText(table_tip_cloth.getValueAt(table_tip_cloth.getSelectedRow(), 0).toString());
            text_tip_cloth.setText(table_tip_cloth.getValueAt(table_tip_cloth.getSelectedRow(), 1).toString());
            pinta_text();
            campos(true);

            if (delet == true && update == true) {
                botones(false, true);

            } else {
                actBotones(update, delet);
            }

        }
    }//GEN-LAST:event_table_tip_clothMouseClicked

    private void txtbuscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscKeyReleased
        // TODO add your handling code here:
        table_tip_cloth.setModel(rmt.setFilas_tip_prend(txtbusc.getText()));
        modelo_tabla();
    }//GEN-LAST:event_txtbuscKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vntana_tipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vntana_tipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vntana_tipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vntana_tipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vntana_tipos dialog = new vntana_tipos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarTodo;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_new;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JLabel lbelbusc;
    private javax.swing.JLabel lblcod;
    private javax.swing.JLabel lblcountipRop;
    private javax.swing.JLabel lbltipr;
    private javax.swing.JPanel panel_all;
    private javax.swing.JPanel pnel_inf;
    private javax.swing.JPanel pnel_inf1;
    private javax.swing.JPanel pnl_cab;
    private javax.swing.JTable table_tip_cloth;
    private javax.swing.JToolBar tbar;
    private javax.swing.JTextField text_cod;
    private javax.swing.JTextField text_tip_cloth;
    private javax.swing.JTextField txtbusc;
    // End of variables declaration//GEN-END:variables
}
