/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.reg_marca_tip;
import Controlador.reg_permisos;
import Controlador.reg_personal;
import Controlador.reg_prod_compras;
import Modelo.Marca;
import Modelo.Permisos;
import Modelo.tipo;
import Modelo.producto_compra;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edgar
 */
public class vntana_ver_prod_compras extends javax.swing.JDialog {

    reg_marca_tip rmt = new reg_marca_tip();
    reg_prod_compras rp = new reg_prod_compras();
    DefaultTableModel datos;
    String ced;

    public vntana_ver_prod_compras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/iconos/tools.png")).getImage());
        try {
            ced = menu_principal.ced_usu;
            loadPermisos(ced);

            modeloTable("");
            cargarCombMarca();
            cargarCombPrendas();

        } catch (Exception err) {
            System.out.println(err);
        }

    }
    ArrayList<Marca> listMarc;

    // ArrayList<Proveedores> listProv;
    ArrayList<tipo> listTipPrend;

    reg_permisos rperm = new reg_permisos();
    reg_personal rpersonal = new reg_personal();
    ArrayList<Permisos> listPerm;

    public void loadPermisos(String ced) {//Busca por cedula
        listPerm = rperm.cargar_permisos(ced);
        for (Permisos per : listPerm) {

            if (per.isPer_regist()) {
                // btn_nuevo.setEnabled(true);
            }
            if (per.isPer_udate()) {
                //btn_actualizar.setEnabled(true);
                // update = true;
            }
            if (per.isPer_delete()) {
                System.out.println("Ingresa al eliminar");
                //btn_delete.setEnabled(true);
                // delet = true;
            }
        }
    }

    public void modeloTable(String dato) {
        load_table(dato);
        modelo_tabla();

    }

    public void modelo_tabla() {
        try {
            table_prod.getColumnModel().getColumn(0).setPreferredWidth(3);
            table_prod.getColumnModel().getColumn(1).setPreferredWidth(10);
            table_prod.getColumnModel().getColumn(2).setPreferredWidth(30);
            table_prod.getColumnModel().getColumn(3).setPreferredWidth(100);
            table_prod.getColumnModel().getColumn(4).setPreferredWidth(60);
            table_prod.getColumnModel().getColumn(5).setPreferredWidth(60);
            table_prod.getColumnModel().getColumn(6).setPreferredWidth(15);
            table_prod.getColumnModel().getColumn(7).setPreferredWidth(100);
            table_prod.getColumnModel().getColumn(8).setPreferredWidth(40);
            table_prod.getTableHeader().setBackground(Color.decode("#666666"));
            table_prod.getTableHeader().setForeground(Color.white);

            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            table_prod.getColumnModel().getColumn(0).setCellRenderer(tcr);
        } catch (Exception err) {
        }

    }

    public void cargarCombMarca() {
        cmb_marca.removeAllItems();
        cmb_marca.addItem("");
        listMarc = rmt.CargarListMarca("");
        for (Marca m : listMarc) {
            cmb_marca.addItem(m.getNom_marca());

        }
    }

    public void cargarCombPrendas() {
        cmb_tip_rop.removeAllItems();
        cmb_tip_rop.addItem("");
        listTipPrend = rmt.LoadListTip("");
        for (tipo tp : listTipPrend) {
            cmb_tip_rop.addItem(tp.getDescrip());
            // cmb_tip_rop.addItem(tp.getNom_prenda());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    ArrayList<producto_compra> listprod;
    public static String codigo;

    public void load_table(String dato) {
        datos = rp.label_table_compra();
        Object[] data = new Object[10];
        listprod = rp.llenar_prod(rp.busc_cod_c(dato));
        for (producto_compra pr : listprod) {
            data[0] = pr.getNum_prod();
            data[1] = pr.getCod_prod();
            data[2] = rmt.ObtNomMarca(pr.getCod_marca() + "");
            data[3] = rmt.ObtNomTip(pr.getCod_tip_prend() + "");
            data[4] = pr.getPrec_cmpra();
            data[5] = pr.getDescuento();
            data[6] = pr.isIva();
            data[7] = pr.getDescripcion();
            data[8] = pr.getObserv();
            datos.addRow(data);
            table_prod.setModel(datos);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_cabez = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnl_all = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tbar = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        text_buscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmb_marca = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmb_tip_rop = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_all = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_rfres = new javax.swing.JButton();
        btn_productos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prod = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de Productos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_cabez.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Listado de Productos");

        javax.swing.GroupLayout panel_cabezLayout = new javax.swing.GroupLayout(panel_cabez);
        panel_cabez.setLayout(panel_cabezLayout);
        panel_cabezLayout.setHorizontalGroup(
            panel_cabezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cabezLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addContainerGap(640, Short.MAX_VALUE))
        );
        panel_cabezLayout.setVerticalGroup(
            panel_cabezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panel_cabez, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 30));

        pnl_all.setBackground(new java.awt.Color(204, 204, 204));
        pnl_all.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Doble clic para seleccionar");
        pnl_all.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        getContentPane().add(pnl_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 790, 30));

        tbar.setBackground(new java.awt.Color(204, 204, 204));
        tbar.setRollover(true);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Código/Nombre:");
        tbar.add(jLabel3);

        text_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_buscarActionPerformed(evt);
            }
        });
        text_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_buscarKeyReleased(evt);
            }
        });
        tbar.add(text_buscar);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Marca");
        tbar.add(jLabel5);

        tbar.add(cmb_marca);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Tipo");
        tbar.add(jLabel2);

        cmb_tip_rop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tip_ropActionPerformed(evt);
            }
        });
        tbar.add(cmb_tip_rop);
        tbar.add(jSeparator2);

        btn_all.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
        btn_all.setText("Buscar");
        btn_all.setFocusable(false);
        btn_all.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_all.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allActionPerformed(evt);
            }
        });
        tbar.add(btn_all);
        tbar.add(jSeparator1);

        btn_rfres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sincronizar.png"))); // NOI18N
        btn_rfres.setText("Refres");
        btn_rfres.setFocusable(false);
        btn_rfres.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_rfres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rfresActionPerformed(evt);
            }
        });
        tbar.add(btn_rfres);

        btn_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/productos.png"))); // NOI18N
        btn_productos.setText("Productos");
        btn_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productosActionPerformed(evt);
            }
        });
        tbar.add(btn_productos);

        getContentPane().add(tbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 790, 40));

        table_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_prodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_prod);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 770, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_prodMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            codigo = (table_prod.getValueAt(table_prod.getSelectedRow(), 1).toString());
            dispose(); //cerrar el diálogo
        }
    }//GEN-LAST:event_table_prodMouseClicked

    private void text_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_buscarKeyReleased
        // TODO add your handling code here:

        modeloTable(text_buscar.getText());
    }//GEN-LAST:event_text_buscarKeyReleased

    private void cmb_tip_ropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tip_ropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tip_ropActionPerformed

    private void btn_rfresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rfresActionPerformed
        // TODO add your handling code here:

        modeloTable("");


    }//GEN-LAST:event_btn_rfresActionPerformed

    private void btn_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productosActionPerformed
        // TODO add your handling code here:
        vntana_productos_bodega dlg = new vntana_productos_bodega(null, false);
        dlg.setModal(true); //no permite acceder a otros formularios hasta que se cierre
        dlg.setVisible(true);
        modeloTable("");

    }//GEN-LAST:event_btn_productosActionPerformed

    private void text_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_buscarActionPerformed

    private void btn_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allActionPerformed
        // TODO add your handling code here:

        //  load_table(cmb_marca.getSelectedItem().toString());
        load_table(cmb_tip_rop.getSelectedItem().toString());


    }//GEN-LAST:event_btn_allActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vntana_ver_prod_compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vntana_ver_prod_compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vntana_ver_prod_compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vntana_ver_prod_compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vntana_ver_prod_compras dialog = new vntana_ver_prod_compras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_all;
    private javax.swing.JButton btn_productos;
    private javax.swing.JButton btn_rfres;
    private javax.swing.JComboBox cmb_marca;
    private javax.swing.JComboBox cmb_tip_rop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPanel panel_cabez;
    private javax.swing.JPanel pnl_all;
    private javax.swing.JTable table_prod;
    private javax.swing.JToolBar tbar;
    private javax.swing.JTextField text_buscar;
    // End of variables declaration//GEN-END:variables
}
